# @name webhookList
GET {{ $dotenv %baseUrl }}/api/webhook/listRegistered?listTitle={{ $dotenv %listTitle }} HTTP/1.1
Accept: application/json

###

# @name webhookShow
GET {{ $dotenv %baseUrl }}/api/webhook/showRegistered?listTitle={{ $dotenv %listTitle }}&notificationUrl={{ $dotenv %notificationUrl }} HTTP/1.1
Accept: application/json

###

#@webhookId = {{ webhookShow.response.body.$.id }}
@webhookId = 6bc8e6c8-c338-4886-99c0-32db0434c302

# @name webhookRemove
POST {{ $dotenv %baseUrl }}/api/webhook/removeRegistered?listTitle={{ $dotenv %listTitle }}&webhookId={{webhookId}} HTTP/1.1

###

POST {{ $dotenv %baseUrl }}/api/webhook/register?listTitle={{ $dotenv %listTitle }}&notificationUrl={{ $dotenv %notificationUrl }} HTTP/1.1

###

